### ISSUE TITLE
xtquant的版本太新了。

### ISSUE THREAD

**Issue by hexstarry** [vnpy/vnpy_xt#27]
xtquant_230825b，对应当前QMT券商版公版的下载python库

券商版会有版本升级跟不上的情况，通常请使用这个公版版本以保证兼容性.

是否考虑维护一个xtquant_230825b版本以便大多数券商版可以使用？

**Comment by vnpy** [comment]
vnpy_xt仅针对【迅投研】数据服务开发，目前没有支持券商QMT系统的规划
